site_name: OnBoard
site_description: Modern onboarding framework for Roblox
site_author: Henrycooper9
site_url: https://henrycooper9.github.io/Onboard/

repo_name: henrycooper9/Onboard
repo_url: https://github.com/henrycooper9/Onboard

theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
    accent: indigo

  features:
    - navigation.instant
    - navigation.expand
    - navigation.sections
    - navigation.top
    - toc.follow
    - content.code.copy
    - content.tabs.link
    - search.highlight
    - search.suggest

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - Configuration: config.md
  - API: api.md